module.exports = {
  FETCHING_TRANSACTION: 'FETCHING_TRANSACTION',
  FETCHED_TRANSACTION: 'FETCHED_TRANSACTION',
  APPLY_FILTER: 'APPLY_FILTER',
  CLEAR_FILTER: 'CLEAR_FILTER',

  ACTIVE_MEMBER: 'ACTIVE_MEMBER',
  ACTIVE_TRANSACTION: 'ACTIVE_TRANSACTION',

  MAIN_FETCH_ERROR: 'MAIN_FETCH_ERROR',
};
